### ISSUE TITLE
Migrate genomics features out of WDKClient

### ISSUE THREAD

**Issue by jtlong3rd** [VEuPathDB/WDKClient#179]
These should be moved to ApiCommonWebsite.

- [x] User Comments
- [x] Genomics Summary Views ("BLAST" and "Genome View")
- [x] Step Analysis Plugins

This should be done after #180

**Comment by jernestmyers** [comment]
@jtlong3rd Is `Genomics Summary Views` referring to the migration of [this directory and its contents](https://github.com/VEuPathDB/WDKClient/tree/master/Client/src/Views/ResultTableSummaryView) to `ApiCommonWebsite`? Or is it [this directory](https://github.com/VEuPathDB/WDKClient/tree/master/Client/src/Actions/SummaryView)?

And is `User Comments` referring to the migration of any file prefixed `UserComment`, which live in multiple directories like `Actions`, `Controllers`, `StoreModules` and two subdirectories in the `Views` directory (and possibly more which can be searched for in VSCode).

**Comment by jtlong3rd** [comment]
@jernestmyers You're spot-on about User Comments - the goal here would be to migrate the components and redux actions/state associated with the two "User Comments" pages, links to which can be found on [record pages](https://plasmodb.org/plasmo/app/record/gene/PcyM_MT03400#UserComments):

1. Clicking on "Add a comment" will take you to the "user comment form," where you can add a new comment or edit an existing one.
2. Clicking on a link in the "Column ID" column takes you to the "user comment 'show' page," where you can view all the record's user comments.

**Comment by jtlong3rd** [comment]
As far as `Genomics Summary Views`, let me first clarify that a "summary view" is one of the 3 tabs in this screenshot:

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/15959217/163040999-f284dd33-5c5b-4a24-b05f-6ce7bd68725b.png">

[The first directory you were asking about](https://github.com/VEuPathDB/WDKClient/tree/master/Client/src/Views/ResultTableSummaryView) is the components for the "default" summary view, which is here under a tab called "Gene Results." Components and redux state for this summary view will stay in `WDKClient` because this summary view is available for all our WDK-powered sites, not just genomics sites.

`Genomics Summary Views` refers to two summary views which are exclusive to genomics sites: "BLAST" and "Genome View."

You'll be moving the components and redux actions/state associated with these two summary views to `ApiCommonWebsite`.

For example, in the [second directory you were asking about](https://github.com/VEuPathDB/WDKClient/tree/master/Client/src/Actions/SummaryView), these two files contain the redux actions for the `Genomics Summary Views`, and so will be migrated to `ApiCommonWebsite`:

```
BlastSummaryViewActions.ts
GenomeSummaryViewActions.ts
```

(The third file, `ResultTableSummaryViewActions.ts` is the redux actions for the default summary view, and so will stay in `WDKClient`.)
