### ISSUE TITLE
issue with all studies column sorting

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/WDKClient#192]
see https://redmine.apidb.org/issues/43707

Sorting by decending order gives blank cells --> large # --> small # instead of large # --> small # --> blank cells  for the following columns:

Participants
Households
Observations
Samples
Variables
The new calculated access statistics variables (Total requests, Approved requests, Percent approved) are not displaying this same sorting pattern.

There is another issue where both blank cells and cells with NA are considered "zero" and so the blank cells do not sort with other blank cells, NA cells do not sort with other NA cells

**Comment by dmfalke** [comment]
Sorting is done in https://github.com/VEuPathDB/WDKClient/blob/9c40c4c66b91f8bec8a0dde50a46af9d1cd4a182/Client/src/Components/DataTable/DataTable.tsx

**Comment by SAK22** [comment]
Looks good to me
