### ISSUE TITLE
TypeError thrown if user sorts by a column and then removes that column

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/WDKClient#202]
`sortingAttribute` is undefined when a user removes the column that the `DataTable` is currently sorted by, which results in a `TypeError`.

Here's how to replicate the behavior:
1. Click to sort a column
2. Proceed to remove that same column
3. An error message will show

These two screenshots show the error both on my dev site and the currently-deployed production build:

![image](https://user-images.githubusercontent.com/69446567/161763949-7d6955d4-37be-4e52-874e-f31932db046f.png)
![image](https://user-images.githubusercontent.com/69446567/161764616-ab0af41d-150a-42cc-80d7-569c059c043d.png)

**Comment by danicahelb** [comment]
I'm still seeing this issue in sorting the all studies table & then removing the column I sorted the table by

**Comment by dmfalke** [comment]
> I'm still seeing this issue in sorting the all studies table & then removing the column I sorted the table by

For what it's worth, this issue also exists on production genomic sites (https://plasmodb.org/plasmo/app/search/dataset/AllDatasets/result).

**Comment by jernestmyers** [comment]
The mistake is that `sortingAttribute` is expected to be an object in the `makeSortKeys` function. However, during the guard against `null` sortingAttributes, I mistakenly passed in only a property attribute (the `name` attribute, specifically):
```
const sortingAttribute = visibleAttributes.find(attribute => attribute.name === sorting[0].attributeName)
const sortKeys = makeSortKeys(sortingAttribute ? sortingAttribute : visibleAttributes[0].name, customSortBys);
 ```
 By assigning just `visibleAttributes[0]`, we would pass in the appropriate object representing the first column.
 
 My mistake should never have worked during testing, so that part still puzzles me.

**Comment by SAK22** [comment]
Looks good
