### ISSUE TITLE
feature.microbiome FARMM, multifilters dont have data, wrong UI message

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/WDKClient#255]
<img width="1180" alt="Screen Shot 2022-10-28 at 3 39 05 PM" src="https://user-images.githubusercontent.com/16354313/198726836-567d7050-3db0-49f4-867d-fee96689581a.png">

**Comment by sweverschulman** [comment]
FARMM study now have multifilter data and can confirm that it is showing up. However I cannot confirm that if there is an error the correct UI error message will be displayed. @aurreco-uga please let know if this is enough to approve this ticket.
