### ISSUE TITLE
wdk result table: Do Not truncate IDs

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/WDKClient#260]

**Comment by aurreco-uga** [comment]
![Image](https://user-images.githubusercontent.com/16354313/204306384-cf679824-2856-4996-aa56-fcdd3f46eb4d.png)

**Comment by dmfalke** [comment]
I think [the CSS we use for truncation](https://github.com/VEuPathDB/WDKClient/blob/f4534e906c0f55a1971753ffd8e9262f85aee4dd/Client/src/Views/ResultTableSummaryView/AttributeCell.tsx#L22) is causing problems here. The behavior we want is to only truncate if the content exceeds a specific width. I think https://github.com/VEuPathDB/WDKClient/blob/43a3e90db7d4b3cfa0ebef97c36a9af4cbc543fd/Client/src/Hooks/Overflow.ts#L20-L54 might be of use: only use the overflow CSS if the content is overflowing.
