### ISSUE TITLE
Feb21-2023-rendering problems in wdk results (2 cases: toxo: overlapping columns, ortho:lack of completion)

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/WDKClient#283]
users at workshop have rendering problems in wdk results

toxo browser
Browser information: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15

ortho browser
Browser information: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

Toxo
<img width="1406" alt="wdk-result-overflow" src="https://user-images.githubusercontent.com/16354313/220372749-6cd1d311-6c0b-4e4a-bad8-1eead3154d18.png">

Ortho
<img width="1416" alt="ortho-wdk-result-rendering-div" src="https://user-images.githubusercontent.com/16354313/220372772-ca17d375-eb57-42cb-9c69-a426312fc14b.png">

Correct Ortho
![correct-ortho-result](https://user-images.githubusercontent.com/16354313/220373738-ed8ff674-2f0d-4f8d-b724-736c9ce4caf1.png)

**Comment by jernestmyers** [comment]
Regarding the Ortho issue, I was able to replicate the issue by using the public strategy `Brucei & donovani & cruzi`. I observed in the React dev tools that the HTML string used in the `alveolata` column defines the CSS styles for the tooltips and percent-bar viz. No other columns defined these styles, so removing that column broke the styling in all columns.

![image](https://user-images.githubusercontent.com/69446567/220383288-e291e4cb-477c-40f8-8f33-2cb399261b97.png)

**Comment by aurreco-uga** [comment]
i was also able to replicate the first issue
it relates to when sorting a column, we get longer values that requires a table column width adjustment that does not happen.
1. i run a search (genes by organism)
2. closed the org filter
3. sort by prod description

**Comment by dmfalke** [comment]
I opened two separate issues for these. I'm closing this one.
